// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";

/**
 * Actions omitted from a decision list are treated as rejected.
 */
export type ActionDecision = { actionId: string, decision: Decision, };
