// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirewallTarget } from "./FirewallTarget";
import type { ProcessIdentity } from "./ProcessIdentity";
import type { TrafficDirection } from "./TrafficDirection";

export type Action = { "type": "terminateProcess", target: ProcessIdentity, } | { "type": "forceKillProcess", target: ProcessIdentity, } | { "type": "setProcessPriority", target: ProcessIdentity, nice: number, } | { "type": "trashPaths", paths: Array<string>, } | { "type": "movePaths", paths: Array<string>, destinationDir: string, } | { "type": "addFirewallRule", target: FirewallTarget, direction: TrafficDirection, } | { "type": "removeFirewallRule", ruleId: string, };
