// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { ItemOutcome } from "./ItemOutcome";
import type { Metric } from "./Metric";
import type { Origin } from "./Origin";
import type { OutcomeStatus } from "./OutcomeStatus";

export type ActionOutcome = { action: Action, origin: Origin, status: OutcomeStatus, items: Array<ItemOutcome>, 
/**
 * Measured, not estimated: e.g. volume used % before and after a trash batch.
 */
before: Array<Metric>, after: Array<Metric>, 
/**
 * "Moved 14 items (8.7 GB) to Trash. Macintosh HD is now 62% used."
 */
summary: string, auditId: number, finishedAtMs: number, };
