// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { ActionRisk } from "./ActionRisk";
import type { Metric } from "./Metric";
import type { Origin } from "./Origin";
import type { PreviewTarget } from "./PreviewTarget";
import type { Reversibility } from "./Reversibility";

export type ActionPreview = { 
/**
 * Single-use; expires at `expires_at_ms`.
 */
token: string, 
/**
 * Normalized action (paths canonicalized, identities resolved).
 */
action: Action, origin: Origin, 
/**
 * "Force kill Google Chrome Helper (PID 4821)".
 */
title: string, 
/**
 * Plain-language statement of exactly what will happen.
 */
description: string, targets: Array<PreviewTarget>, 
/**
 * "Frees 2.3 GB", "Last modified 47 days ago".
 */
impact: Array<Metric>, estimatedBytesFreed: number | null, risk: ActionRisk, reversibility: Reversibility, 
/**
 * e.g. "Owned by root — administrator authorization will be requested", "System process".
 */
warnings: Array<string>, requiresElevation: boolean, createdAtMs: number, expiresAtMs: number, };
