// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Address class of the remote end; only `Public` addresses are geolocated and drawn on the map.
 */
export type AddrScope = "loopback" | "private" | "linkLocal" | "multicast" | "unspecified" | "public";
