// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { Plan } from "./Plan";
import type { ProviderId } from "./ProviderId";
import type { StopReason } from "./StopReason";
import type { ToolAccess } from "./ToolAccess";
import type { JsonValue } from "./serde_json/JsonValue";

export type AgentEvent = { "type": "turnStarted", turnId: string, provider: ProviderId, model: string, } | { "type": "textDelta", text: string, } | { "type": "toolCallStarted", callId: string, name: string, access: ToolAccess, input: JsonValue, } | { "type": "toolCallFinished", callId: string, ok: boolean, 
/**
 * One-line human summary ("412 processes", "Scanned 214 GB").
 */
summary: string, } | { "type": "planProposed", plan: Plan, } | { "type": "planUpdated", plan: Plan, } | { "type": "turnFinished", stopReason: StopReason, } | { "type": "error", error: ErrorPayload, };
