// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

/**
 * Non-secret settings, persisted as JSON in the app config dir. API keys live only in the keychain.
 */
export type AgentSettings = { activeProvider: ProviderId, 
/**
 * Model chosen per provider, so switching providers restores the previous choice.
 */
selectedModels: { [key in ProviderId]?: string }, ollamaBaseUrl: string, 
/**
 * Upper bound on model↔tool round-trips per user message.
 */
maxToolRounds: number, };
