// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEvent } from "./AgentEvent";

export type AgentStreamPayload = { conversationId: string, event: AgentEvent, };
