// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { AuditStatus } from "./AuditStatus";
import type { Metric } from "./Metric";
import type { Origin } from "./Origin";

export type AuditEntry = { id: number, tsMs: number, origin: Origin, 
/**
 * The user's natural-language request for agent actions; `None` for direct UI actions.
 */
trigger: string | null, action: Action, title: string, status: AuditStatus, summary: string, bytesFreed: number | null, 
/**
 * Original locations of anything moved to trash or elsewhere, for recovery.
 */
affectedPaths: Array<string>, before: Array<Metric>, after: Array<Metric>, };
