// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OriginFilter } from "./OriginFilter";

export type AuditQuery = { limit: number, 
/**
 * Keyset pagination: entries with id < `before_id`.
 */
beforeId: number | null, origin: OriginFilter, };
