// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { Role } from "./Role";

export type ChatMessage = { role: Role, content: Array<ContentBlock>, };
