// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupCategory } from "./CleanupCategory";

export type CleanupSuggestion = { id: string, category: CleanupCategory, path: string, sizeBytes: number, itemCount: number, lastModified: number | null, lastAccessed: number | null, 
/**
 * Why this is usually safe to remove and what regenerates it. Always a suggestion.
 */
rationale: string, 
/**
 * False for categories Sentinel will not act on (e.g. Trash, whose removal is permanent).
 */
actionable: boolean, };
