// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much Sentinel actually knows about an explanation.
 */
export type Confidence = "known" | "likely" | "unknown";
