// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";

/**
 * Explanation of one socket: who the other end is, what that endpoint is usually for, and an
 * explicit statement about encryption. Never names a browser tab or a URL, because the OS does
 * not attribute a connection to either.
 */
export type ConnectionExplanation = { 
/**
 * "Secure web traffic to Apple", "Domain name lookup".
 */
headline: string, 
/**
 * Plain sentences: who owns the other end, what this is usually for, and — for encrypted
 * ports — that the contents cannot be read.
 */
detail: string, 
/**
 * Plain name of the service on the port: "secure web", "domain name lookup".
 */
service: string | null, 
/**
 * What that destination is usually used for, when the catalog recognises it.
 */
purpose: string | null, confidence: Confidence, 
/**
 * True when the port is one that is encrypted by definition (HTTPS, QUIC, SSH, IMAPS, …).
 */
encrypted: boolean, };
