// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";
import type { JsonValue } from "./serde_json/JsonValue";

export type ContentBlock = { "type": "text", text: string, } | { "type": "toolUse", id: string, name: string, input: JsonValue, } | { "type": "toolResult", toolUseId: string, 
/**
 * JSON-encoded tool output (or error message when `is_error`).
 */
content: string, isError: boolean, } | { "type": "providerData", provider: ProviderId, data: JsonValue, };
