// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateGroup } from "./DuplicateGroup";

export type DuplicateReport = { jobId: string, scanId: string, groups: Array<DuplicateGroup>, reclaimableBytes: number, durationMs: number, };
