// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";

export type DuplicateGroup = { 
/**
 * BLAKE3 of full contents, hex.
 */
hash: string, sizeBytes: number, files: Array<FileEntry>, 
/**
 * size * (copies - 1).
 */
reclaimableBytes: number, };
