// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicatePhase } from "./DuplicatePhase";

export type DuplicateProgress = { jobId: string, phase: DuplicatePhase, candidates: number, hashed: number, bytesHashed: number, error: string | null, };
