// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape sent to the frontend: the tagged error plus its rendered message.
 */
export type ErrorPayload = { message: string, } & ({ "code": "permissionDenied", operation: string, target: string | null, hint: string | null, } | { "code": "processNotFound", pid: number, } | { "code": "processChanged", pid: number, } | { "code": "pathNotFound", path: string, } | { "code": "unavailable", feature: string, reason: string, } | { "code": "elevationDeclined", operation: string, } | { "code": "invalidInput", message: string, } | { "code": "actionTokenInvalid" } | { "code": "cancelled" } | { "code": "network", message: string, } | { "code": "provider", provider: string, status: number | null, message: string, } | { "code": "io", message: string, path: string | null, } | { "code": "internal", message: string, });
