// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKindGroup } from "./FileKindGroup";

export type ExtensionStat = { 
/**
 * Lower-cased, without dot; `None` for files without an extension.
 */
extension: string | null, fileKind: FileKindGroup, bytes: number, count: number, };
