// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKindGroup } from "./FileKindGroup";

export type FileEntry = { nodeId: number, path: string, name: string, sizeBytes: number, modified: number | null, accessed: number | null, extension: string | null, fileKind: FileKindGroup, };
