// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse file type used for treemap colouring and the by-type breakdown.
 */
export type FileKindGroup = "image" | "video" | "audio" | "document" | "archive" | "code" | "application" | "diskImage" | "data" | "system" | "other";
