// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirewallBackend } from "./FirewallBackend";

export type FirewallStatus = { backend: FirewallBackend | null, available: boolean, 
/**
 * e.g. pf disabled, Windows Firewall off for the active profile.
 */
firewallEnabled: boolean | null, requiresElevation: boolean, note: string | null, };
