// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirewallBackend } from "./FirewallBackend";
import type { FirewallTarget } from "./FirewallTarget";
import type { TrafficDirection } from "./TrafficDirection";

/**
 * A rule Sentinel created. Sentinel only lists and removes its own rules, never the user's others.
 */
export type FirewallRule = { id: string, target: FirewallTarget, direction: TrafficDirection, backend: FirewallBackend, createdAtMs: number, 
/**
 * Audit entry that created it.
 */
auditId: number | null, 
/**
 * Whether the rule is currently loaded in the OS firewall (pf anchors are cleared on reboot).
 */
active: boolean, };
