// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportProtocol } from "./TransportProtocol";

export type FirewallTarget = { "type": "remoteIp", ip: string, } | { "type": "localPort", port: number, protocol: TransportProtocol, };
