// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local IP-geolocation database (DB-IP City Lite, mmdb format). Downloaded once; lookups never
 * leave the machine.
 */
export type GeoDbStatus = { "state": "missing" } | { "state": "downloading", downloadedBytes: number, totalBytes: number | null, } | { "state": "ready", buildDate: string | null, attribution: string, } | { "state": "failed", message: string, };
