// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeLocationSource } from "./HomeLocationSource";

/**
 * Approximate position of this machine for the map origin, derived from the system time zone
 * (or a user override) — no external lookup.
 */
export type HomeLocation = { lat: number, lon: number, label: string, source: HomeLocationSource, };
