// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";

export type ItemOutcome = { label: string, success: boolean, error: ErrorPayload | null, };
