// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";

export type ItemOutcome = { label: string, 
/**
 * The exact path this item acted on, when the action was path-based (trash, move). `None`
 * for a process or firewall item, whose `label` is not a path. Lets the UI map a batch
 * result back to the exact row it started from instead of matching display labels.
 */
path: string | null, success: boolean, error: ErrorPayload | null, };
