// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadKind } from "./LoadKind";

export type LoadAverage = { one: number, five: number, fifteen: number, kind: LoadKind, };
