// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryBreakdown = { total: number, used: number, available: number, free: number, 
/**
 * File cache / standby list. `None` where the OS does not separate it.
 */
cached: number | null, 
/**
 * macOS compressor, Linux zswap.
 */
compressed: number | null, 
/**
 * macOS wired, Windows non-paged pool.
 */
wired: number | null, swapTotal: number, swapUsed: number, };
