// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricUnit } from "./MetricUnit";

export type Metric = { key: string, label: string, value: number, unit: MetricUnit, };
