// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetThroughput = { 
/**
 * Bytes per second (not bits) received, summed across every network interface on this
 * machine — Wi-Fi, Ethernet, VPN — with loopback excluded.
 */
rxBps: number, 
/**
 * Bytes per second (not bits) sent, same scope as `rx_bps`.
 */
txBps: number, 
/**
 * Cumulative bytes received since the interface came up (normally since the machine booted),
 * same scope as `rx_bps`.
 */
rxTotal: number, txTotal: number, };
