// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetThroughput } from "./NetThroughput";
import type { SocketEntry } from "./SocketEntry";
import type { TrafficSource } from "./TrafficSource";

export type NetworkSnapshot = { tsMs: number, sockets: Array<SocketEntry>, throughput: NetThroughput, trafficSource: TrafficSource, };
