// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo";

export type OllamaStatus = { installed: boolean, running: boolean, version: string | null, baseUrl: string, 
/**
 * Locally pulled models, with tool-calling support flagged.
 */
models: Array<ModelInfo>, };
