// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenFileKind } from "./OpenFileKind";

export type OpenFile = { fd: number | null, kind: OpenFileKind, path: string | null, };
