// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Origin = { "type": "user" } | { "type": "agent", conversationId: string, planId: string, provider: string, model: string, 
/**
 * The user message that produced the plan; recorded as the audit trigger.
 */
request: string, };
