// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirewallStatus } from "./FirewallStatus";
import type { PermissionState } from "./PermissionState";
import type { Platform } from "./Platform";

export type PermissionStatus = { platform: Platform, fullDiskAccess: PermissionState, 
/**
 * Sentinel itself is running elevated.
 */
runningElevated: boolean, 
/**
 * An elevation mechanism exists (osascript admin prompt / pkexec / UAC).
 */
canRequestElevation: boolean, firewall: FirewallStatus, };
