// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionOutcome } from "./ActionOutcome";
import type { ErrorPayload } from "./ErrorPayload";

export type PlanActionState = { "state": "pending" } | { "state": "rejected" } | { "state": "executing" } | { "state": "succeeded", outcome: ActionOutcome, } | { "state": "failed", error: ErrorPayload, } | { "state": "expired" };
