// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionPreview } from "./ActionPreview";
import type { PlanActionState } from "./PlanActionState";

export type PlanAction = { id: string, rationale: string, preview: ActionPreview, state: PlanActionState, };
