// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAction } from "./PlanAction";
import type { PlanStatus } from "./PlanStatus";

export type Plan = { id: string, conversationId: string, 
/**
 * The user message that produced this plan.
 */
request: string, 
/**
 * Model's plain-language explanation shown above the cards.
 */
explanation: string, actions: Array<PlanAction>, status: PlanStatus, createdAtMs: number, };
