// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewTarget = { 
/**
 * "Google Chrome Helper (PID 4821)", "~/Library/Caches/com.old.app".
 */
label: string, detail: string | null, sizeBytes: number | null, 
/**
 * Target could not be validated (vanished, unreadable); it will be skipped on commit.
 */
problem: string | null, };
