// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-process ring buffer point backing the detail panel's 60s mini graph.
 */
export type ProcessHistoryPoint = { tsMs: number, cpuPercent: number, memoryRss: number, };
