// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInfo } from "./ProcessInfo";

export type ProcessSnapshot = { tsMs: number, processes: Array<ProcessInfo>, logicalCores: number, totalMemory: number, };
