// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A PID alone is not a safe action target: PIDs are recycled. Every process action carries the
 * start time observed at preview so execution can refuse if the PID now belongs to another process.
 */
export type ProcessIdentity = { pid: number, startTime: number, };
