// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { ProcessCategory } from "./ProcessCategory";
import type { ProcessRole } from "./ProcessRole";
import type { QuitSafety } from "./QuitSafety";

/**
 * Full explanation of one process.
 */
export type ProcessExplanation = { 
/**
 * "Brave Browser — web page".
 */
headline: string, 
/**
 * One or two plain sentences. Inferences start with "Looks like"; unknowns say so.
 */
detail: string, role: ProcessRole, category: ProcessCategory, quitSafety: QuitSafety, 
/**
 * What actually happens if you quit it, and the better alternative when there is one.
 */
quitNote: string, 
/**
 * The raw facts this was built from: flags, bundle, parent, user, path.
 */
evidence: Array<string>, appName: string | null, confidence: Confidence, };
