// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessStatus } from "./ProcessStatus";
import type { ProcessSummary } from "./ProcessSummary";

export type ProcessInfo = { pid: number, ppid: number | null, name: string, cmd: Array<string>, exe: string | null, user: string | null, status: ProcessStatus, 
/**
 * Top-style percentage: 100 = one full logical core, so it can exceed 100 on multi-core machines.
 */
cpuPercent: number, 
/**
 * Exponential moving average of `cpu_percent` (~10 sample time constant).
 */
cpuPercentAvg: number, memoryRss: number, memoryVirtual: number, startTime: number, runTimeSecs: number, 
/**
 * `None` when the OS does not expose it for this process (e.g. insufficient privileges).
 */
threadCount: number | null, fdCount: number | null, 
/**
 * Unix nice value (-20..=19). On Windows the priority class is mapped onto this scale.
 */
nice: number | null, 
/**
 * Plain-language explanation of what this process is, for the table subtitle and app
 * grouping. `Default` (empty headline, `Confidence::Unknown`) for a moment before the
 * runtime's enrichment pass fills it in.
 */
summary: ProcessSummary, };
