// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a process does inside its application or the system.
 */
export type ProcessRole = "mainApp" | "renderer" | "extension" | "gpu" | "networkService" | "audioService" | "utility" | "helper" | "daemon" | "kernel" | "shell" | "interpreter" | "unknown";
