// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { OpenFile } from "./OpenFile";
import type { ProcessExplanation } from "./ProcessExplanation";
import type { ProcessInfo } from "./ProcessInfo";
import type { SocketEntry } from "./SocketEntry";

export type ProcessDetail = { info: ProcessInfo, openFiles: Array<OpenFile>, 
/**
 * Set when handles could not be listed (typically another user's process without elevation).
 */
openFilesError: ErrorPayload | null, connections: Array<SocketEntry>, 
/**
 * Whether graceful termination will close a window rather than send a signal.
 */
hasWindow: boolean, 
/**
 * Full plain-language explanation, including the "Is it safe to quit?" note and the
 * evidence it was built from. `info.summary` carries the same headline/role/safety, computed
 * once here.
 */
explanation: ProcessExplanation, };
