// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { ProcessCategory } from "./ProcessCategory";
import type { ProcessRole } from "./ProcessRole";
import type { QuitSafety } from "./QuitSafety";

/**
 * Compact explanation carried by every row of the 1 Hz process snapshot: enough for the table's
 * plain subtitle, app grouping and safety hint. The full [`ProcessExplanation`] (with detail,
 * quit note and evidence) comes with `ProcessDetail`, on demand.
 */
export type ProcessSummary = { 
/**
 * One short line in ordinary English: "Brave Browser — web page".
 */
headline: string, 
/**
 * Owning application for helpers, so 40 helpers group under one app.
 */
appName: string | null, role: ProcessRole, category: ProcessCategory, quitSafety: QuitSafety, confidence: Confidence, };
