// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which family a process belongs to, for grouping and filtering.
 */
export type ProcessCategory = "browser" | "userApp" | "appHelper" | "osService" | "kernel" | "developer" | "security" | "unknown";
