// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adding a provider = new variant + one `AgentBackend` adapter + descriptor entry.
 */
export type ProviderId = "ollama" | "anthropic" | "openai" | "gemini";
