// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo";
import type { ProviderId } from "./ProviderId";
import type { ProviderKind } from "./ProviderKind";

export type ProviderDescriptor = { id: ProviderId, displayName: string, kind: ProviderKind, requiresApiKey: boolean, 
/**
 * Shown before the live model list loads (or when offline).
 */
suggestedModels: Array<ModelInfo>, 
/**
 * Chat badge copy, e.g. "Requests sent to Anthropic API".
 */
dataNotice: string, };
