// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens if this process is stopped. Drives the "Is it safe to quit?" copy in the table,
 * the detail drawer and the confirm dialog.
 */
export type QuitSafety = "systemCritical" | "osService" | "appHelper" | "userApp" | "background" | "unknown";
