// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadAverage } from "./LoadAverage";
import type { MemoryBreakdown } from "./MemoryBreakdown";
import type { NetThroughput } from "./NetThroughput";
import type { ThermalSample } from "./ThermalSample";

export type ResourceSample = { tsMs: number, 
/**
 * 0..=100 across all cores.
 */
cpuTotal: number, 
/**
 * 0..=100 per logical core, index = core number.
 */
perCore: Array<number>, memory: MemoryBreakdown, load: LoadAverage | null, thermal: ThermalSample | null, network: NetThroughput, };
