// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamKind } from "./StreamKind";

/**
 * Only subscribed streams are sampled, so a hidden Network view costs nothing.
 */
export type SamplingConfig = { 
/**
 * 500 ("high refresh"), 1000 (default), or 2000.
 */
intervalMs: number, streams: Array<StreamKind>, };
