// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeNode } from "./TreeNode";

/**
 * Streamed while walking: the top of the tree with sizes discovered so far.
 */
export type ScanPartial = { scanId: string, root: TreeNode, };
