// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupSuggestion } from "./CleanupSuggestion";
import type { ExtensionStat } from "./ExtensionStat";
import type { FileEntry } from "./FileEntry";

export type ScanSummary = { scanId: string, root: string, startedAtMs: number, durationMs: number, totalBytes: number, fileCount: number, dirCount: number, unreadableEntries: number, 
/**
 * First few unreadable directories, to point the user at Full Disk Access etc.
 */
unreadableSamples: Array<string>, byExtension: Array<ExtensionStat>, 
/**
 * Top 100 by size.
 */
largestFiles: Array<FileEntry>, suggestions: Array<CleanupSuggestion>, };
