// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanPhase } from "./ScanPhase";

export type ScanProgress = { scanId: string, phase: ScanPhase, filesScanned: number, dirsScanned: number, bytesScanned: number, unreadableEntries: number, currentPath: string | null, elapsedMs: number, error: string | null, };
