// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanRequest = { root: string, 
/**
 * Descend into other mounted volumes under `root`.
 */
crossMounts: boolean, };
