// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every fallible backend call returns this. Variants carry enough context for the UI to render a
 * specific message ("Permission denied reading /Library/Caches — grant Full Disk Access") instead
 * of a generic failure. Serialized with a `code` discriminator.
 */
export type SentinelError = { "code": "permissionDenied", operation: string, target: string | null, hint: string | null, } | { "code": "processNotFound", pid: number, } | { "code": "processChanged", pid: number, } | { "code": "pathNotFound", path: string, } | { "code": "unavailable", feature: string, reason: string, } | { "code": "elevationDeclined", operation: string, } | { "code": "invalidInput", message: string, } | { "code": "actionTokenInvalid" } | { "code": "cancelled" } | { "code": "network", message: string, } | { "code": "provider", provider: string, status: number | null, message: string, } | { "code": "io", message: string, path: string | null, } | { "code": "internal", message: string, };
