// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddrScope } from "./AddrScope";
import type { GeoLocation } from "./GeoLocation";
import type { IpFamily } from "./IpFamily";
import type { TcpState } from "./TcpState";
import type { TransportProtocol } from "./TransportProtocol";

/**
 * Enriched socket row sent to the UI (process name, reverse DNS, geo, traffic).
 */
export type SocketEntry = { 
/**
 * Stable across samples: `proto|local:port|remote:port|pid`.
 */
id: string, protocol: TransportProtocol, family: IpFamily, localAddr: string, localPort: number, remoteAddr: string | null, remotePort: number | null, remoteScope: AddrScope | null, 
/**
 * `None` for UDP.
 */
state: TcpState | null, pid: number | null, processName: string | null, 
/**
 * Reverse-DNS result; resolved asynchronously, so often `None` on first sight.
 */
remoteHost: string | null, geo: GeoLocation | null, 
/**
 * Cumulative bytes. Kernel counters where exposed, otherwise since Sentinel first saw the socket.
 */
bytesIn: number | null, bytesOut: number | null, rxBps: number | null, txBps: number | null, firstSeenMs: number, };
