// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddrScope } from "./AddrScope";
import type { ConnectionExplanation } from "./ConnectionExplanation";
import type { GeoLocation } from "./GeoLocation";
import type { IpFamily } from "./IpFamily";
import type { TcpState } from "./TcpState";
import type { TransportProtocol } from "./TransportProtocol";

/**
 * Enriched socket row sent to the UI (process name, reverse DNS, geo, traffic).
 */
export type SocketEntry = { 
/**
 * Stable across samples: `proto|local:port|remote:port|pid`.
 */
id: string, protocol: TransportProtocol, family: IpFamily, localAddr: string, localPort: number, remoteAddr: string | null, remotePort: number | null, remoteScope: AddrScope | null, 
/**
 * `None` for UDP.
 */
state: TcpState | null, pid: number | null, processName: string | null, 
/**
 * Start time of the owning process, so an action taken from the Network view can build a
 * `ProcessIdentity` without a separate lookup. `None` when `pid` is `None` or the owning
 * process could not be resolved at sample time.
 */
processStartTime: number | null, 
/**
 * Reverse-DNS result; resolved asynchronously, so often `None` on first sight.
 */
remoteHost: string | null, geo: GeoLocation | null, 
/**
 * Cumulative bytes. Kernel counters where exposed, otherwise since Sentinel first saw the socket.
 */
bytesIn: number | null, bytesOut: number | null, 
/**
 * Bytes per second (not bits) received since the previous sample. `None` when this platform
 * or privilege level only exposes cumulative bytes (see `TrafficSource`).
 */
rxBps: number | null, 
/**
 * Bytes per second (not bits) sent since the previous sample.
 */
txBps: number | null, firstSeenMs: number, 
/**
 * Plain-language explanation of who the other end is and what it is usually for.
 */
explanation: ConnectionExplanation, };
