// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StopReason = { "type": "endTurn" } | { "type": "toolUse" } | { "type": "maxTokens" } | { "type": "refusal" } | { "type": "other", raw: string, };
