// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform } from "./Platform";

export type SystemInfo = { platform: Platform, hostname: string | null, osName: string, osVersion: string | null, kernelVersion: string | null, arch: string, cpuBrand: string, physicalCores: number | null, logicalCores: number, totalMemory: number, totalSwap: number, bootTime: number, };
