// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a graceful terminate was delivered, reported back so the UI can say exactly what happened.
 */
export type TerminateMethod = "signal" | "windowClose" | "terminateProcess";
