// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FanReading } from "./FanReading";
import type { TemperatureReading } from "./TemperatureReading";

/**
 * Only sensors the OS exposes through public APIs. The whole field is `None` when nothing is
 * readable, and the UI hides the panel rather than showing zeros.
 */
export type ThermalSample = { temperatures: Array<TemperatureReading>, fans: Array<FanReading>, };
