// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Granularity of traffic accounting the current OS/privilege level supports.
 */
export type TrafficSource = "perConnection" | "perProcess" | "interfaceOnly";
