// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plan } from "./Plan";
import type { ToolAccess } from "./ToolAccess";

/**
 * Rendered conversation history, for restoring the chat panel.
 */
export type TranscriptItem = { "type": "user", text: string, tsMs: number, } | { "type": "assistant", text: string, tsMs: number, } | { "type": "toolCall", callId: string, name: string, access: ToolAccess, ok: boolean | null, summary: string | null, } | { "type": "plan", plan: Plan, };
