// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupCategory } from "./CleanupCategory";
import type { FileKindGroup } from "./FileKindGroup";
import type { NodeKind } from "./NodeKind";

export type TreeNode = { id: number, name: string, path: string, kind: NodeKind, sizeBytes: number, 
/**
 * Files beneath this node (1 for a file).
 */
itemCount: number, modified: number | null, accessed: number | null, extension: string | null, fileKind: FileKindGroup | null, category: CleanupCategory | null, 
/**
 * Entries under this directory that could not be read (permission denied, vanished mid-scan).
 */
unreadableEntries: number, hasChildren: boolean, 
/**
 * `None` when not loaded (beyond the requested depth); sorted by size descending.
 */
children: Array<TreeNode> | null, };
