// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeQuery = { scanId: string, 
/**
 * `None` = scan root.
 */
nodeId: number | null, depth: number, maxChildren: number, };
