// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeInfo = { mountPoint: string, name: string, fileSystem: string, totalBytes: number, availableBytes: number, isRemovable: boolean, 
/**
 * The volume holding the OS / user home.
 */
isSystem: boolean, };
