//! Rule rendering for every firewall backend, plus parsing of what each backend reports back.
//! Pure functions: everything here is unit-tested on every host.

use std::net::IpAddr;

use crate::error::{CoreResult, SentinelError};
use crate::model::{FirewallRule, FirewallTarget, TrafficDirection, TransportProtocol};

pub const PF_ANCHOR: &str = "com.apple/250.sentinel";
pub const NFT_TABLE: &str = "sentinel";
pub const IPTABLES_IN: &str = "SENTINEL_IN";
pub const IPTABLES_OUT: &str = "SENTINEL_OUT";
const LABEL_PREFIX: &str = "sentinel:";
pub const WINDOWS_RULE_PREFIX: &str = "Sentinel-";

/// Rule ids are generated by Sentinel as lowercase hex; anything else is rejected before it can
/// reach a privileged shell.
pub fn validate_id(id: &str) -> CoreResult<()> {
    if id.is_empty() || id.len() > 32 || !id.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(SentinelError::invalid(format!(
            "invalid firewall rule id {id:?}"
        )));
    }
    Ok(())
}

pub fn validate_target(target: &FirewallTarget) -> CoreResult<()> {
    match target {
        FirewallTarget::RemoteIp { ip } => {
            let addr: IpAddr = ip
                .trim()
                .parse()
                .map_err(|_| SentinelError::invalid(format!("{ip} is not an IP address")))?;
            if addr.is_unspecified() {
                return Err(SentinelError::invalid(
                    "blocking the unspecified address would block all traffic",
                ));
            }
            if addr.is_loopback() {
                return Err(SentinelError::invalid(
                    "blocking loopback traffic would break local services, including Sentinel",
                ));
            }
            Ok(())
        }
        FirewallTarget::LocalPort { port, .. } => {
            if *port == 0 {
                return Err(SentinelError::invalid("port must be between 1 and 65535"));
            }
            Ok(())
        }
    }
}

fn parsed_ip(ip: &str) -> CoreResult<IpAddr> {
    ip.trim()
        .parse()
        .map_err(|_| SentinelError::invalid(format!("{ip} is not an IP address")))
}

fn proto(protocol: TransportProtocol) -> &'static str {
    match protocol {
        TransportProtocol::Tcp => "tcp",
        TransportProtocol::Udp => "udp",
    }
}

fn inbound(direction: TrafficDirection) -> bool {
    matches!(
        direction,
        TrafficDirection::Inbound | TrafficDirection::Both
    )
}

fn outbound(direction: TrafficDirection) -> bool {
    matches!(
        direction,
        TrafficDirection::Outbound | TrafficDirection::Both
    )
}

/// pf ruleset for the Sentinel anchor (loaded with `pfctl -a com.apple/250.sentinel -f -`).
pub fn pf_ruleset(rules: &[FirewallRule]) -> CoreResult<String> {
    let mut out = String::from("# Managed by Sentinel; changes are overwritten.\n");
    for rule in rules {
        validate_id(&rule.id)?;
        validate_target(&rule.target)?;
        let label = format!("label \"{LABEL_PREFIX}{}\"", rule.id);
        match &rule.target {
            FirewallTarget::RemoteIp { ip } => {
                let ip = parsed_ip(ip)?;
                if inbound(rule.direction) {
                    out.push_str(&format!("block drop in quick from {ip} to any {label}\n"));
                }
                if outbound(rule.direction) {
                    out.push_str(&format!("block drop out quick from any to {ip} {label}\n"));
                }
            }
            FirewallTarget::LocalPort { port, protocol } => {
                let p = proto(*protocol);
                if inbound(rule.direction) {
                    out.push_str(&format!(
                        "block drop in quick proto {p} from any to any port {port} {label}\n"
                    ));
                }
                if outbound(rule.direction) {
                    out.push_str(&format!(
                        "block drop out quick proto {p} from any port {port} to any {label}\n"
                    ));
                }
            }
        }
    }
    Ok(out)
}

/// Rule ids carried by `label "sentinel:<id>"` in `pfctl -a … -s rules` output.
pub fn pf_rule_ids(output: &str) -> Vec<String> {
    labelled_ids(output)
}

fn labelled_ids(output: &str) -> Vec<String> {
    let mut ids: Vec<String> = output
        .match_indices(LABEL_PREFIX)
        .filter_map(|(index, _)| {
            let rest = &output[index + LABEL_PREFIX.len()..];
            let id: String = rest.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
            (!id.is_empty()).then_some(id)
        })
        .collect();
    ids.sort();
    ids.dedup();
    ids
}

/// Atomic nftables transaction replacing the `inet sentinel` table (`nft -f -`). With no rules
/// the table is removed entirely.
pub fn nft_ruleset(rules: &[FirewallRule]) -> CoreResult<String> {
    let mut input = Vec::new();
    let mut output = Vec::new();
    for rule in rules {
        validate_id(&rule.id)?;
        validate_target(&rule.target)?;
        let comment = format!("comment \"{LABEL_PREFIX}{}\"", rule.id);
        match &rule.target {
            FirewallTarget::RemoteIp { ip } => {
                let ip = parsed_ip(ip)?;
                let family = if ip.is_ipv4() { "ip" } else { "ip6" };
                if inbound(rule.direction) {
                    input.push(format!("{family} saddr {ip} drop {comment}"));
                }
                if outbound(rule.direction) {
                    output.push(format!("{family} daddr {ip} drop {comment}"));
                }
            }
            FirewallTarget::LocalPort { port, protocol } => {
                let p = proto(*protocol);
                if inbound(rule.direction) {
                    input.push(format!("{p} dport {port} drop {comment}"));
                }
                if outbound(rule.direction) {
                    output.push(format!("{p} sport {port} drop {comment}"));
                }
            }
        }
    }
    let mut out = format!("table inet {NFT_TABLE}\ndelete table inet {NFT_TABLE}\n");
    if rules.is_empty() {
        return Ok(out);
    }
    out.push_str(&format!("table inet {NFT_TABLE} {{\n"));
    for (chain, hook, lines) in [("input", "input", &input), ("output", "output", &output)] {
        out.push_str(&format!(
            "  chain {chain} {{\n    type filter hook {hook} priority filter - 10; policy accept;\n"
        ));
        for line in lines {
            out.push_str(&format!("    {line}\n"));
        }
        out.push_str("  }\n");
    }
    out.push_str("}\n");
    Ok(out)
}

/// Rule ids in `nft list table inet sentinel` output.
pub fn nft_rule_ids(output: &str) -> Vec<String> {
    labelled_ids(output)
}

/// Shell script rebuilding Sentinel's iptables/ip6tables chains.
pub fn iptables_script(rules: &[FirewallRule]) -> CoreResult<String> {
    let mut script = String::from("set -e\n");
    for tool in ["iptables", "ip6tables"] {
        for (chain, parent) in [(IPTABLES_IN, "INPUT"), (IPTABLES_OUT, "OUTPUT")] {
            script.push_str(&format!(
                "{tool} -N {chain} 2>/dev/null || true\n{tool} -F {chain}\n{tool} -C {parent} -j {chain} 2>/dev/null || {tool} -I {parent} -j {chain}\n"
            ));
        }
    }
    for rule in rules {
        validate_id(&rule.id)?;
        validate_target(&rule.target)?;
        let comment = format!("-m comment --comment {LABEL_PREFIX}{}", rule.id);
        match &rule.target {
            FirewallTarget::RemoteIp { ip } => {
                let ip = parsed_ip(ip)?;
                let tool = if ip.is_ipv4() {
                    "iptables"
                } else {
                    "ip6tables"
                };
                if inbound(rule.direction) {
                    script.push_str(&format!(
                        "{tool} -A {IPTABLES_IN} -s {ip} {comment} -j DROP\n"
                    ));
                }
                if outbound(rule.direction) {
                    script.push_str(&format!(
                        "{tool} -A {IPTABLES_OUT} -d {ip} {comment} -j DROP\n"
                    ));
                }
            }
            FirewallTarget::LocalPort { port, protocol } => {
                let p = proto(*protocol);
                for tool in ["iptables", "ip6tables"] {
                    if inbound(rule.direction) {
                        script.push_str(&format!(
                            "{tool} -A {IPTABLES_IN} -p {p} --dport {port} {comment} -j DROP\n"
                        ));
                    }
                    if outbound(rule.direction) {
                        script.push_str(&format!(
                            "{tool} -A {IPTABLES_OUT} -p {p} --sport {port} {comment} -j DROP\n"
                        ));
                    }
                }
            }
        }
    }
    Ok(script)
}

/// Rule ids in `iptables -S` output.
pub fn iptables_rule_ids(output: &str) -> Vec<String> {
    labelled_ids(output)
}

/// `netsh advfirewall firewall add rule` argument lists, one per direction.
pub fn netsh_add_commands(rule: &FirewallRule) -> CoreResult<Vec<Vec<String>>> {
    validate_id(&rule.id)?;
    validate_target(&rule.target)?;
    let name = format!("name={WINDOWS_RULE_PREFIX}{}", rule.id);
    let mut commands = Vec::new();
    for (enabled, dir) in [
        (inbound(rule.direction), "in"),
        (outbound(rule.direction), "out"),
    ] {
        if !enabled {
            continue;
        }
        let mut args: Vec<String> = ["advfirewall", "firewall", "add", "rule"]
            .iter()
            .map(|s| (*s).to_owned())
            .collect();
        args.push(name.clone());
        args.push(format!("dir={dir}"));
        args.push("action=block".to_owned());
        args.push("enable=yes".to_owned());
        match &rule.target {
            FirewallTarget::RemoteIp { ip } => {
                args.push(format!("remoteip={}", parsed_ip(ip)?));
            }
            FirewallTarget::LocalPort { port, protocol } => {
                args.push(format!(
                    "protocol={}",
                    proto(*protocol).to_ascii_uppercase()
                ));
                args.push(format!("localport={port}"));
            }
        }
        args.push("description=Added by Sentinel".to_owned());
        commands.push(args);
    }
    Ok(commands)
}

pub fn netsh_delete_command(rule_id: &str) -> CoreResult<Vec<String>> {
    validate_id(rule_id)?;
    Ok(vec![
        "advfirewall".into(),
        "firewall".into(),
        "delete".into(),
        "rule".into(),
        format!("name={WINDOWS_RULE_PREFIX}{rule_id}"),
    ])
}

/// Ids of `Sentinel-<id>` rules in `netsh advfirewall firewall show rule name=all` output (the
/// field label is localized, the rule name is not).
pub fn netsh_rule_ids(output: &str) -> Vec<String> {
    let mut ids: Vec<String> = output
        .match_indices(WINDOWS_RULE_PREFIX)
        .filter_map(|(index, _)| {
            let rest = &output[index + WINDOWS_RULE_PREFIX.len()..];
            let id: String = rest.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
            let terminated = rest[id.len()..]
                .chars()
                .next()
                .is_none_or(|c| c.is_whitespace());
            (!id.is_empty() && terminated).then_some(id)
        })
        .collect();
    ids.sort();
    ids.dedup();
    ids
}

/// A Windows command line argument for `Start-Process -ArgumentList` inside a single-quoted
/// PowerShell string.
pub fn powershell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', "''"))
}

/// A string literal inside an AppleScript `do shell script "…"`.
pub fn applescript_quote(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}

/// A POSIX shell single-quoted word.
pub fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::FirewallBackend;

    fn rule(id: &str, target: FirewallTarget, direction: TrafficDirection) -> FirewallRule {
        FirewallRule {
            id: id.into(),
            target,
            direction,
            backend: FirewallBackend::Pf,
            created_at_ms: 0,
            audit_id: None,
            active: false,
        }
    }

    fn ip(ip: &str) -> FirewallTarget {
        FirewallTarget::RemoteIp { ip: ip.into() }
    }

    fn port(port: u16, protocol: TransportProtocol) -> FirewallTarget {
        FirewallTarget::LocalPort { port, protocol }
    }

    #[test]
    fn pf_renders_every_target_and_direction() {
        let rules = vec![
            rule("a1", ip("203.0.113.9"), TrafficDirection::Both),
            rule("b2", ip("2606:4700::1111"), TrafficDirection::Outbound),
            rule(
                "c3",
                port(5432, TransportProtocol::Tcp),
                TrafficDirection::Inbound,
            ),
            rule(
                "d4",
                port(53, TransportProtocol::Udp),
                TrafficDirection::Both,
            ),
        ];
        let text = pf_ruleset(&rules).unwrap();
        let expected = "# Managed by Sentinel; changes are overwritten.\n\
block drop in quick from 203.0.113.9 to any label \"sentinel:a1\"\n\
block drop out quick from any to 203.0.113.9 label \"sentinel:a1\"\n\
block drop out quick from any to 2606:4700::1111 label \"sentinel:b2\"\n\
block drop in quick proto tcp from any to any port 5432 label \"sentinel:c3\"\n\
block drop in quick proto udp from any to any port 53 label \"sentinel:d4\"\n\
block drop out quick proto udp from any port 53 to any label \"sentinel:d4\"\n";
        assert_eq!(text, expected);
        assert_eq!(pf_rule_ids(&text), vec!["a1", "b2", "c3", "d4"]);
        assert_eq!(pf_ruleset(&[]).unwrap().lines().count(), 1);
    }

    #[test]
    fn nft_renders_atomic_table_replacement() {
        let rules = vec![
            rule("a1", ip("198.51.100.4"), TrafficDirection::Inbound),
            rule("b2", ip("2001:db8::5"), TrafficDirection::Both),
            rule(
                "c3",
                port(8080, TransportProtocol::Tcp),
                TrafficDirection::Outbound,
            ),
        ];
        let text = nft_ruleset(&rules).unwrap();
        assert!(text.starts_with(
            "table inet sentinel\ndelete table inet sentinel\ntable inet sentinel {\n"
        ));
        assert!(text.contains("chain input {\n    type filter hook input priority filter - 10; policy accept;\n    ip saddr 198.51.100.4 drop comment \"sentinel:a1\"\n    ip6 saddr 2001:db8::5 drop comment \"sentinel:b2\"\n  }"));
        assert!(text.contains("chain output {\n    type filter hook output priority filter - 10; policy accept;\n    ip6 daddr 2001:db8::5 drop comment \"sentinel:b2\"\n    tcp sport 8080 drop comment \"sentinel:c3\"\n  }"));
        assert_eq!(nft_rule_ids(&text), vec!["a1", "b2", "c3"]);
        assert_eq!(
            nft_ruleset(&[]).unwrap(),
            "table inet sentinel\ndelete table inet sentinel\n"
        );
    }

    #[test]
    fn iptables_script_rebuilds_chains() {
        let rules = vec![
            rule("a1", ip("192.0.2.1"), TrafficDirection::Outbound),
            rule(
                "b2",
                port(22, TransportProtocol::Tcp),
                TrafficDirection::Inbound,
            ),
        ];
        let script = iptables_script(&rules).unwrap();
        assert!(script.contains("iptables -N SENTINEL_IN 2>/dev/null || true\niptables -F SENTINEL_IN\niptables -C INPUT -j SENTINEL_IN 2>/dev/null || iptables -I INPUT -j SENTINEL_IN\n"));
        assert!(script.contains(
            "iptables -A SENTINEL_OUT -d 192.0.2.1 -m comment --comment sentinel:a1 -j DROP\n"
        ));
        assert!(script.contains(
            "iptables -A SENTINEL_IN -p tcp --dport 22 -m comment --comment sentinel:b2 -j DROP\n"
        ));
        assert!(script.contains(
            "ip6tables -A SENTINEL_IN -p tcp --dport 22 -m comment --comment sentinel:b2 -j DROP\n"
        ));
        assert!(!script.contains("ip6tables -A SENTINEL_OUT -d 192.0.2.1"));
        let listing =
            "-A SENTINEL_IN -p tcp -m tcp --dport 22 -m comment --comment sentinel:b2 -j DROP\n";
        assert_eq!(iptables_rule_ids(listing), vec!["b2"]);
    }

    #[test]
    fn netsh_commands_and_listing() {
        let both = rule("abc123", ip("203.0.113.7"), TrafficDirection::Both);
        let commands = netsh_add_commands(&both).unwrap();
        assert_eq!(commands.len(), 2);
        assert_eq!(
            commands[0],
            vec![
                "advfirewall",
                "firewall",
                "add",
                "rule",
                "name=Sentinel-abc123",
                "dir=in",
                "action=block",
                "enable=yes",
                "remoteip=203.0.113.7",
                "description=Added by Sentinel"
            ]
        );
        assert_eq!(commands[1][5], "dir=out");
        let port_rule = rule(
            "ff",
            port(3389, TransportProtocol::Tcp),
            TrafficDirection::Inbound,
        );
        let commands = netsh_add_commands(&port_rule).unwrap();
        assert_eq!(commands.len(), 1);
        assert!(commands[0].contains(&"protocol=TCP".to_owned()));
        assert!(commands[0].contains(&"localport=3389".to_owned()));
        assert_eq!(netsh_delete_command("ff").unwrap()[4], "name=Sentinel-ff");

        let listing = "\r\nRule Name:                            Sentinel-abc123\r\n----\r\nEnabled: Yes\r\n\r\nRegelname:                            Sentinel-ff\r\nRule Name:  Sentinel-Other thing\r\n";
        assert_eq!(netsh_rule_ids(listing), vec!["abc123", "ff"]);
    }

    #[test]
    fn rejects_unsafe_input() {
        assert!(validate_id("abc; rm -rf /").is_err());
        assert!(validate_id("").is_err());
        assert!(
            pf_ruleset(&[rule(
                "a1",
                ip("1.2.3.4; pass all"),
                TrafficDirection::Inbound
            )])
            .is_err()
        );
        assert!(validate_target(&ip("0.0.0.0")).is_err());
        assert!(validate_target(&ip("127.0.0.1")).is_err());
        assert!(validate_target(&port(0, TransportProtocol::Tcp)).is_err());
        assert!(validate_target(&ip("8.8.8.8")).is_ok());
    }

    #[test]
    fn quoting_helpers_escape() {
        assert_eq!(shell_quote("a'b"), "'a'\\''b'");
        assert_eq!(
            applescript_quote("say \"hi\" \\"),
            "\"say \\\"hi\\\" \\\\\""
        );
        assert_eq!(powershell_quote("it's"), "'it''s'");
    }
}
